name: Publish to npm
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: false
        default: "Manual"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Auto-increment Version and Publish
        run: |
          npm version patch --no-git-tag-version
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
